### ISSUE TITLE
[TODO] Global

### ISSUE THREAD

**Issue by Ydalb** [Ydalb/mapicoin#1]
# A faire
- [ ] Liste d'experts annonces
- [ ] Lancer les recherches leboncoin côté client, grosse refonte en perspective (full JS ?)
- [ ] Passer sous CakePHP
- [ ] Menu contextuel sur la carte (Localiser moi ici, ...) : http://googlemapsmania.blogspot.fr/2012/04/create-google-maps-context-menu.html
# A voir / éventuellement
- [ ] Vérifier la récupération de coordonnées, des fois on doit tomber sur des code != 200, il faudrait re-tenter 1 fois quand ça foire (google limit' ?)
- [ ] Couleurs des marqueurs en fonction des prix + baromètre sur la carte
# Fait
- [x] Pouvoir changer sa géolocalisation par une adresse en dur / un drag'n'drop
- [x] Changer le géocoding par une vraie BDD (cf MP HFR)
- [x] Récupérer le nombre de photo
- [x] Aligner les photos verticalement
- [x] Changer le géocoding pour Google + Système de Cache
- [x] Nombre d'annonce regroupé sous une pine
- [x] Ruban pour DL le plugin : https://github.com/simonwhitaker/github-fork-ribbon-css
- [x] Proposez la géolocalisation avec le navigateur
- [x] Distance par rapport sa géolocalisation
- [x] Nouveau design avec carte google map en pleine page et panel d'annonces sur la gauche
- [x] Mettre un overlay transparent sur la carte pour focus l'utilisateur sur le champ de recherche
- [x] Affichage du prix moyen
- [x] Bouton "Me géolocaliser"
